from formsaurus.tests.welcome_screen import *
from formsaurus.tests.multiple_choice import *
from formsaurus.tests.yes_no import *
from formsaurus.tests.phone_number import *
from formsaurus.tests.short_text import *
from formsaurus.tests.long_text import *
from formsaurus.tests.statement import *
from formsaurus.tests.picture_choice import *
from formsaurus.tests.email import *
from formsaurus.tests.opinion_scale import *
from formsaurus.tests.rating import *
from formsaurus.tests.date import *
from formsaurus.tests.number import *
from formsaurus.tests.dropdown import *
from formsaurus.tests.legal import *
from formsaurus.tests.website import *