# Generated by Django 3.1.1 on 2020-09-11 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('choice', models.CharField(max_length=1024)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('question_type', models.CharField(choices=[('WS', 'Welcome Screen'), ('TS', 'Thank You Screen'), ('MC', 'Multiple Choice'), ('PN', 'Phone Number'), ('ST', 'Short Text'), ('LT', 'Long Text'), ('S_', 'Statement'), ('PC', 'Picture Choice'), ('YN', 'Yes/No'), ('E_', 'Email'), ('OS', 'Opinion Scale'), ('R_', 'Rating'), ('D_', 'Date'), ('N_', 'Number'), ('DD', 'Dropdown'), ('L_', 'Legal'), ('FU', 'File Upload'), ('P_', 'Payment'), ('W_', 'Website')], max_length=2)),
                ('required', models.BooleanField()),
                ('next_question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_question', to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField()),
                ('jump_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_to', to='formsaurus.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YesNoParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YesNoAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('yes', models.BooleanField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WelcomeParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('button_label', models.CharField(max_length=128)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThankYouParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('show_button', models.BooleanField()),
                ('button_label', models.CharField(max_length=128)),
                ('button_link', models.URLField(blank=True, default=None, null=True)),
                ('show_social_media', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField()),
                ('operand', models.CharField(blank=True, choices=[('OS', 'Or'), ('AND', 'And')], default=None, max_length=3, null=True)),
                ('match', models.CharField(choices=[('EQ', 'Equal'), ('NEQ', 'Not Equal'), ('SW', 'Starts With'), ('EW', 'Ends With'), ('C', 'Contains')], max_length=3)),
                ('pattern', models.TextField()),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.ruleset')),
                ('tested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('first_question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_question', to='formsaurus.question')),
                ('last_question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_question', to='formsaurus.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.survey'),
        ),
        migrations.CreateModel(
            name='StatementParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('button_label', models.CharField(max_length=128)),
                ('show_quotation_mark', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShortTextParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('limit_character', models.BooleanField()),
                ('limit', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShortTextAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('short_text', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RatingParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('number_of_steps', models.PositiveSmallIntegerField()),
                ('shape', models.CharField(choices=[('S_', 'Stars'), ('T_', 'Thumbs')], max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.survey'),
        ),
        migrations.CreateModel(
            name='PictureChoiceParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('multiple_selection', models.BooleanField()),
                ('randomize', models.BooleanField()),
                ('other_option', models.BooleanField()),
                ('show_labels', models.BooleanField()),
                ('supersize', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PictureChoiceAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('choices', models.ManyToManyField(to='formsaurus.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('default_country_code', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stripe_token', models.CharField(max_length=256)),
                ('button_label', models.CharField(max_length=128)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionScaleParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('start_at_one', models.BooleanField()),
                ('number_of_steps', models.PositiveSmallIntegerField()),
                ('show_labels', models.BooleanField()),
                ('left_label', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('center_label', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('right_label', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionScaleAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('opinion', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('enable_min', models.BooleanField()),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True)),
                ('enable_max', models.BooleanField()),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField()),
                ('operand', models.CharField(blank=True, choices=[('OS', 'Or'), ('AND', 'And')], default=None, max_length=3, null=True)),
                ('match', models.CharField(choices=[('EQ', 'Equal'), ('NEQ', 'Not Equal'), ('LT', 'Lower Than'), ('LTOEQ', 'Lower Than Or Equal'), ('GT', 'Greater Than'), ('GTOEQ', 'Greater Than Or Equal')], max_length=5)),
                ('pattern', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.ruleset')),
                ('tested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('multiple_selection', models.BooleanField()),
                ('randomize', models.BooleanField()),
                ('other_option', models.BooleanField()),
                ('vertical_alignment', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('other', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('choices', models.ManyToManyField(to='formsaurus.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LongTextParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('limit_character', models.BooleanField()),
                ('limit', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LongTextAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('long_text', models.TextField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('accept', models.BooleanField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiddenField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUploadParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUploadAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DropdownParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('randomize', models.BooleanField()),
                ('alphabetical', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DropdownAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('other', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('choices', models.ManyToManyField(to='formsaurus.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('video_url', models.URLField(blank=True, default=None, null=True)),
                ('date_format', models.CharField(choices=[('A', 'YYYYMMDD'), ('B', 'DDMMYYYY'), ('C', 'MMDDYYYY')], max_length=1)),
                ('date_separator', models.CharField(choices=[('-', '-'), ('.', '.'), ('/', '/')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField()),
                ('operand', models.CharField(blank=True, choices=[('OS', 'Or'), ('AND', 'And')], default=None, max_length=3, null=True)),
                ('match', models.CharField(choices=[('IS', 'Is'), ('ISN', 'Is Not')], max_length=3)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.choice')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.ruleset')),
                ('tested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question'),
        ),
        migrations.CreateModel(
            name='BooleanCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField()),
                ('operand', models.CharField(blank=True, choices=[('OS', 'Or'), ('AND', 'And')], default=None, max_length=3, null=True)),
                ('match', models.CharField(choices=[('IS', 'Is'), ('ISN', 'Is Not')], max_length=3)),
                ('boolean', models.BooleanField()),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.ruleset')),
                ('tested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsaurus.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
