# Generated by Django 3.1.1 on 2020-10-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsaurus', '0002_auto_20201012_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('WS', 'Welcome Screen'), ('MC', 'Multiple Choice'), ('PN', 'Phone Number'), ('ST', 'Short Text'), ('LT', 'Long Text'), ('S_', 'Statement'), ('PC', 'Picture Choice'), ('YN', 'Yes/No'), ('E_', 'Email'), ('OS', 'Opinion Scale'), ('R_', 'Rating'), ('D_', 'Date'), ('N_', 'Number'), ('DD', 'Dropdown'), ('L_', 'Legal'), ('FU', 'File Upload'), ('P_', 'Payment'), ('W_', 'Website'), ('TS', 'Thank You Screen')], max_length=2),
        ),
    ]
